/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminChannelsRouteImport } from './routes/admin.channels'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminPoolsRouteImport } from './routes/admin.pools'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminQualityRouteImport } from './routes/admin.quality'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAffRouteImport } from './routes/portal.aff'
import { Route as PortalKeysRouteImport } from './routes/portal.keys'
import { Route as PortalLedgerRouteImport } from './routes/portal.ledger'
import { Route as PortalLogsRouteImport } from './routes/portal.logs'
import { Route as PortalSecurityRouteImport } from './routes/portal.security'
import { Route as PortalTeamsRouteImport } from './routes/portal.teams'
import { Route as PortalTopupRouteImport } from './routes/portal.topup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoolsRoute = AdminPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQualityRoute = AdminQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAffRoute = PortalAffRouteImport.update({
  id: '/aff',
  path: '/aff',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKeysRoute = PortalKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLedgerRoute = PortalLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLogsRoute = PortalLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSecurityRoute = PortalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTeamsRoute = PortalTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTopupRoute = PortalTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pools': typeof AdminPoolsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/aff': typeof PortalAffRoute
  '/portal/keys': typeof PortalKeysRoute
  '/portal/ledger': typeof PortalLedgerRoute
  '/portal/logs': typeof PortalLogsRoute
  '/portal/security': typeof PortalSecurityRoute
  '/portal/teams': typeof PortalTeamsRoute
  '/portal/topup': typeof PortalTopupRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pools': typeof AdminPoolsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/aff': typeof PortalAffRoute
  '/portal/keys': typeof PortalKeysRoute
  '/portal/ledger': typeof PortalLedgerRoute
  '/portal/logs': typeof PortalLogsRoute
  '/portal/security': typeof PortalSecurityRoute
  '/portal/teams': typeof PortalTeamsRoute
  '/portal/topup': typeof PortalTopupRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pools': typeof AdminPoolsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/aff': typeof PortalAffRoute
  '/portal/keys': typeof PortalKeysRoute
  '/portal/ledger': typeof PortalLedgerRoute
  '/portal/logs': typeof PortalLogsRoute
  '/portal/security': typeof PortalSecurityRoute
  '/portal/teams': typeof PortalTeamsRoute
  '/portal/topup': typeof PortalTopupRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/pricing'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/codes'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/ops'
    | '/admin/plans'
    | '/admin/pools'
    | '/admin/pricing'
    | '/admin/quality'
    | '/admin/revenue'
    | '/admin/roles'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/portal/aff'
    | '/portal/keys'
    | '/portal/ledger'
    | '/portal/logs'
    | '/portal/security'
    | '/portal/teams'
    | '/portal/topup'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/codes'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/ops'
    | '/admin/plans'
    | '/admin/pools'
    | '/admin/pricing'
    | '/admin/quality'
    | '/admin/revenue'
    | '/admin/roles'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/portal/aff'
    | '/portal/keys'
    | '/portal/ledger'
    | '/portal/logs'
    | '/portal/security'
    | '/portal/teams'
    | '/portal/topup'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/portal'
    | '/pricing'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/codes'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/ops'
    | '/admin/plans'
    | '/admin/pools'
    | '/admin/pricing'
    | '/admin/quality'
    | '/admin/revenue'
    | '/admin/roles'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/portal/aff'
    | '/portal/keys'
    | '/portal/ledger'
    | '/portal/logs'
    | '/portal/security'
    | '/portal/teams'
    | '/portal/topup'
    | '/admin/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/channels': {
      id: '/admin/channels'
      path: '/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pools': {
      id: '/admin/pools'
      path: '/pools'
      fullPath: '/admin/pools'
      preLoaderRoute: typeof AdminPoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quality': {
      id: '/admin/quality'
      path: '/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AdminQualityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/aff': {
      id: '/portal/aff'
      path: '/aff'
      fullPath: '/portal/aff'
      preLoaderRoute: typeof PortalAffRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/keys': {
      id: '/portal/keys'
      path: '/keys'
      fullPath: '/portal/keys'
      preLoaderRoute: typeof PortalKeysRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/ledger': {
      id: '/portal/ledger'
      path: '/ledger'
      fullPath: '/portal/ledger'
      preLoaderRoute: typeof PortalLedgerRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/logs': {
      id: '/portal/logs'
      path: '/logs'
      fullPath: '/portal/logs'
      preLoaderRoute: typeof PortalLogsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/security': {
      id: '/portal/security'
      path: '/security'
      fullPath: '/portal/security'
      preLoaderRoute: typeof PortalSecurityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/teams': {
      id: '/portal/teams'
      path: '/teams'
      fullPath: '/portal/teams'
      preLoaderRoute: typeof PortalTeamsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/topup': {
      id: '/portal/topup'
      path: '/topup'
      fullPath: '/portal/topup'
      preLoaderRoute: typeof PortalTopupRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPoolsRoute: typeof AdminPoolsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminQualityRoute: typeof AdminQualityRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPoolsRoute: AdminPoolsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminQualityRoute: AdminQualityRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAffRoute: typeof PortalAffRoute
  PortalKeysRoute: typeof PortalKeysRoute
  PortalLedgerRoute: typeof PortalLedgerRoute
  PortalLogsRoute: typeof PortalLogsRoute
  PortalSecurityRoute: typeof PortalSecurityRoute
  PortalTeamsRoute: typeof PortalTeamsRoute
  PortalTopupRoute: typeof PortalTopupRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAffRoute: PortalAffRoute,
  PortalKeysRoute: PortalKeysRoute,
  PortalLedgerRoute: PortalLedgerRoute,
  PortalLogsRoute: PortalLogsRoute,
  PortalSecurityRoute: PortalSecurityRoute,
  PortalTeamsRoute: PortalTeamsRoute,
  PortalTopupRoute: PortalTopupRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
