// 集中式 query key 工厂（禁字符串散写）。

export const qk = {
  me: ['me'] as const,
  keys: ['keys'] as const,
  adminChannels: ['admin', 'channels'] as const,
  adminPricingRules: ['admin', 'pricing-rules'] as const,
  adminUsers: (q: string) => ['admin', 'users', q] as const,
  adminRoles: ['admin', 'roles'] as const,
  adminPermissions: ['admin', 'permissions'] as const,
  adminPools: ['admin', 'pools'] as const,
  poolDetail: (code: string) => ['admin', 'pools', 'detail', code] as const,
  audit: (params: string) => ['admin', 'audit', params] as const,
  auditActions: ['admin', 'audit', 'actions'] as const,
  myLogins: ['me', 'logins'] as const,
  myGroups: ['me', 'groups'] as const,
  adminGroups: ['admin', 'groups'] as const,
  adminModels: ['admin', 'models'] as const,
  adminKeys: (userId: number | null, q: string) => ['admin', 'keys', userId, q] as const,
  channelModels: (id: number) => ['admin', 'channel-models', id] as const,
  statsOverview: (days: number) => ['admin', 'stats', 'overview', days] as const,
  myBreakdown: (scope: string, days: number, range = '') => ['me', 'stats', 'breakdown', scope, days, range] as const,
  myActivity: (scope: string, year?: number) => ['me', 'stats', 'activity', scope, year] as const,
  myTeams: ['me', 'teams'] as const,
  teamUsage: (id: number) => ['team', 'usage', id] as const,
  statsChannels: (days: number) => ['admin', 'stats', 'channels', days] as const,
  statsModels: (days: number) => ['admin', 'stats', 'models', days] as const,
  statsMargin: (days: number) => ['admin', 'stats', 'margin', days] as const,
  statsRealtime: ['admin', 'stats', 'realtime'] as const,
  statsErrors: (days: number) => ['admin', 'stats', 'errors', days] as const,
  statsCashflow: (days: number) => ['admin', 'stats', 'cashflow', days] as const,
  statsModelTrend: (days: number) => ['admin', 'stats', 'model-trend', days] as const,
  statsClients: (days: number) => ['admin', 'stats', 'clients', days] as const,
  statsGroups: (days: number) => ['admin', 'stats', 'groups', days] as const,
  statsTrend: (params: string) => ['admin', 'stats', 'trend', params] as const,
  statsBreakdown: (params: string) => ['admin', 'stats', 'breakdown', params] as const,
  statsFlow: (params: string) => ['admin', 'stats', 'flow', params] as const,
  statsInventory: ['admin', 'stats', 'inventory'] as const,
  entityUsage: (kind: string, ids: string, days: number) =>
    ['admin', 'stats', 'entity-usage', kind, ids, days] as const,
  channelTimeline: (id: number, hours: number) =>
    ['admin', 'stats', 'channel-timeline', id, hours] as const,
  diagnose: ['admin', 'diagnose'] as const,
  dlq: (all: boolean) => ['admin', 'dlq', all] as const,
  adminLogs: (params: string) => ['admin', 'logs', params] as const,
  adminLogStat: (params: string) => ['admin', 'logs', 'stat', params] as const,
  reconciliation: ['admin', 'reconciliation'] as const,
  userOverview: (id: number) => ['admin', 'user-overview', id] as const,
  userUsage: (id: number) => ['admin', 'user-usage', id] as const,
  publicPricing: ['public-pricing'] as const,
  notice: ['public-notice'] as const,
  logs: (params: string) => ['logs', params] as const,
  myLedger: ['me', 'ledger'] as const,
  myOrders: ['me', 'orders'] as const,
  setupStatus: ['setup-status'] as const,
  oauthProviders: ['oauth-providers'] as const,
  registrationPolicy: ['registration-policy'] as const,
  oauthExchange: ['oauth-exchange'] as const,
}
